# Generated by Django 4.1.7 on 2024-07-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='uploaded_at',
        ),
    ]
