# Generated by Django 4.1.7 on 2024-07-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0002_remove_imageupload_uploaded_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
